name: Bug report
description: Report a reproducible bug in the portfolio.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide clear reproduction steps and expected vs actual behavior.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the issue.
      placeholder: Contact form fails with 400 when submitting valid data
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, including URLs or section names.
      placeholder: |
        1. Open /#contact
        2. Fill in valid name, email, and message
        3. Click Send Message
        4. See error state
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Form should submit and show success state
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Form resets to idle and does not submit
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome 122, Safari 17.5
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Windows 11, macOS 14, Ubuntu 24.04
  - type: textarea
    id: logs
    attributes:
      label: Console logs or screenshots
      description: Paste relevant logs or screenshots if available.
